import { SmartHouse } from "../components/SmartHouse";
import { Device } from "../components/Device";
import { AirConditioning } from "../components/AirConditioning";
import { Tv } from "../components/Tv";
import { Light } from "../components/Light";

const house = new SmartHouse("my house", "NY, 5th AV", "Oleg Shynkarenko");
window.house = house;
house.addNewDevice(new Tv("Samsung"));
house.addNewDevice(new Tv("Samsung-2"));
house.addNewDevice(new Tv("Samsung-3"));
house.addNewDevice(new Tv("Samsung-4"));
house.addNewDevice(new Tv("Samsung-5"));
house.addNewDevice(new AirConditioning("Cooper and Hunter"));
house.addNewDevice(new AirConditioning("Cooper and Hunter-2"));
house.addNewDevice(new Light("Phillips"));
house.addNewDevice(new Light("Phillips-1"));
house.addNewDevice(new Light("Phillips-2"));
house.addNewDevice(new Light("Phillips-3"));
house.addNewDevice(new Light("Phillips-4"));
house.addNewDevice(new Light("Phillips-5"));
house.addNewDevice(new Light("Phillips-6"));
